#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <time.h>
#include <algorithm>
#include <iterator>
#include <vector>
#include <sstream>
#include <fstream>
#include <sstream>
